version: "3.9"

services:

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_db
    restart: unless-stopped

    ports:
      - "9043:9042"

    environment:
      CASSANDRA_AUTHENTICATOR: "PasswordAuthenticator"
      CASSANDRA_USERNAME: "cassandra_user"
      CASSANDRA_PASSWORD: "securepassword123"
      CASSANDRA_CLUSTER_NAME: "DACExampleCluster"
      CASSANDRA_AUTH_STARTUP_DELAY: 60

    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
