spring:
  application:
    name: connector-example-app

  datasource:
    url: jdbc:mysql://localhost:3306/connectorexampleapp?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://holocron.keross.com/api/platform



ikon:
  user:
    agent: "IKON App Server"
  time-zone: "Asia/Kolkata"
  platform:
    rest: https://holocron.keross.com/api
  logger:
    enabled: false # set true when deployed in dev/uat/prod otherwise set to false if running in local/devtools environment.
  app:
    softwareId: "865798ff-47a9-4911-b82e-d50d6fd7ff87"
    softwareVersion: 1
    softwareName: "connector Example App"
    softwareRepositoryName: "connector-example-app"
  accessmanagement:
    init:
      file: ../../bpmn/project.json

  connector:
    internal-auth:
      tokenUri: https://holocron.keross.com/api/platform/oauth2/token
      clientId: ikon-client-management
      clientSecret: F38Ysb4VEOSXUeISKcMyvpKqxtrIL8nf
      scopes: "internal"
    crypto:
      secretKey: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

logging:
  level:
    com.ikon: DEBUG
  file:
    name: "../logs/${spring.application.name}-app.log"

server:
  address: 0.0.0.0
  port: 8070
