spring:
  application:
    name: dac-example-app

  datasource:
    url: jdbc:mysql://localhost:3306/dacexampleapp?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true

  # If you are using process, uncomment below
  # sql:
  #   init:
  #     schema-locations:
  #       - classpath:activiti.engine.schema.sql
  #     mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ikoncloud-dev.keross.com/ikon-api/platform

  # If you use any one of the below data sources, uncomment data and the respective section.
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: mongopassword123
      authentication-database: admin

    elasticsearch:
      repositories:
        enabled: true

  cassandra:
    contact-points: localhost
    port: 9043
    username: cassandra_user
    password: securepassword123
    keyspace-name: dac_example_app
    schema-action: create-if-not-exists
    local-datacenter: datacenter1
    pool:
      init-query-timeout: 30s

mongodb:
  client:
    settings:
      connection-pool:
        max-size: 500
        min-size: 10
        max-connection-idle-time: 10s
        max-wait-time: 5s

  elasticsearch:
    uris: http://localhost:9200

ikon:
  user:
    agent: "IKON App Server"
  time-zone: "Asia/Kolkata"
  platform:
    rest:
      url: https://ikoncloud-dev.keross.com/ikon-api/platform
  logger:
    enabled: false # set true when deployed in dev/uat/prod otherwise set to false if running in local/devtools environment.
  app:
    softwareId: "865798ff-47a9-4911-b82e-d50d6fd7ff87"
    softwareVersion: 1
    softwareName: "DAC Example App"
    softwareRepositoryName: "dac-example-app"
  accessmanagement:
    init:
      file: ../../bpmn/project.json

  dac:
    # Enable/disable DAC (default: true)
    enabled: true

    # Default batch size for IN clause operations (default: 500)
    default-batch-size: 500

# If you are using process, uncomment below
# processengine:
#   databaseSchemaUpdate: false # possible values: "true", "false", "create-drop"
#   bpmn:
#     enabled: true
#     path: "../../bpmn"
# job:
#   max-pool-size: 100

logging:
  level:
    com.ikon: DEBUG
  file:
    name: "../logs/${spring.application.name}-app.log"

server:
  address: 0.0.0.0
  port: 8070
