apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-configmap
  labels:
    name: {{ include "chart.fullname" . }}-configmap
data:
  application.yml: |
    spring:
      application:
        name: {{repo_name}}

      datasource:
        url: jdbc:mysql://mysql-haproxy.database.svc.cluster.local:3306/{{db_name repo_name}}?createDatabaseIfNotExist=true
        username: system
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connectionTimeout: 20000
          maximumPoolSize: 20
      jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
          ddl-auto: update # Options: none, validate, update, create, create-drop
        show-sql: true
        defer-datasource-initialization: false
        properties:
          hibernate:
            format_sql: true

    # If you are using process, uncomment below
    #   sql:
    #     init:
    #       schema-locations:
    #         - classpath:activiti.engine.schema.sql
    #       mode: always

      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://holocron.keross.com/api/platform

    # If you use any one of the below data sources, uncomment data and the respective section.
      #data:
    # If you are using redis, uncomment below
    #    redis:
    #      host: redis.database.svc.cluster.local
    #      port: 6379
    #      password: ducs8WZf7lJnsHm6
    #      database: 0
    #      lettuce:
    #        pool:
    #          max-active: 10       # Maximum number of connections
    #          max-idle: 8          # Maximum idle connections
    #          min-idle: 2          # Minimum idle connections
    #          max-wait: 5s         # Max wait time for a connection
        
    # If you are using mongodb, uncomment below
    #     mongodb:
    #       host: mongo.database.svc.cluster.loca
    #       port: 27017
    #       username: admin
    #       password: admin
    #       authentication-database: admin
    #   mongodb:
    #     client:
    #       settings:
    #         connection-pool:
    #           max-size: 500           # Maximum connections in the pool
    #           min-size: 10           # Minimum idle connections
    #           max-connection-idle-time: 10s     # Time a connection can be idle before being closed
    #           max-wait-time: 5s

    # If you are using kafka, uncomment below
    #   kafka:
    #     bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    #     properties:
    #       schema:
    #         registry:
    #           url: http://schemaregistry.kafka.svc.cluster.local:8081
    #       specific:
    #         avro:
    #           reader: true
    #     producer:
    #       key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #       value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    #     consumer:
    #       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #       value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    #       group-id: ${spring.application.name}-consumer-group
    #       auto-offset-reset: earliest

      

    ikon:
      user:
        agent: "IKON App Server"
      time-zone: "Asia/Kolkata"
      platform:
        rest:
          url: http://ikon-api-gateway.ikon-platform.svc.cluster.local:8080/api
      logger:
        enabled: false # set true when deployed in dev/uat/prod otherwise set to false if running in local/devtools environment.
      app:
        softwareId: "{{software_id}}"
        softwareVersion: {{version}}
        softwareName: "{{app_name}}"
        softwareRepositoryName: "{{repo_name}}"
        
      accessmanagement:
        init:
          file: ./bpmn/project.json

    # If you are using process, uncomment below
    #   processengine:
    #     databaseSchemaUpdate: false # possible values: "true", "false", "create-drop"
    #     bpmn:
    #       enabled: true
    #       path: ./bpmn
    #   job:
    #     max-pool-size: 100



    logging:
      level:
        com.ikon: DEBUG
      file:
        name: "../logs/${spring.application.name}-app.log"

    server:
      address: ${HOSTNAME}
      port: 8070

    eureka:
        instance:
          hostname: ${HOSTNAME}
          ipAddress: ${{{upper_snake_case repo_name}}_BACKEND_SERVICE_SERVICE_HOST}
          preferIpAddress: true
          instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
        client:
          registerWithEureka: true
          fetchRegistry: true
          serviceUrl:
            defaultZone: http://ikon-discovery-service.ikon-platform.svc.cluster.local:8761/eureka


    management:
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      endpoints:
        web:
          exposure:
            include: health
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true

